Game frame animation
liviucotfas/ase-multimedia pull request #18
Opened 2024-12-19 15:42 UTC by andreiserban123

Buna ziua,

Am realizat modificarile pentru ca mingea din joc sa se miste cu aceeasi viteza indifirent de refresh rate-ul monitorului. Daca ceva nu este ok, va rog sa-mi spuneti pentru a putea corecta

Seara frumoasa,

Andrei Serban

2024-12-22 19:22 UTC, liviucotfas requested changes

2024-12-22 19:22 UTC, liviucotfas commented on Labs/11. Games/code-examples/canvas-game/main.js
> +document.addEventListener("DOMContentLoaded", () => {
Utilizarea evenimentului `DOMContentLoaded` nu ar trebui sa fie necesară în contextul în care script-ul este inclus chiar înainte de </body>

2024-12-22 19:22 UTC, liviucotfas commented on Labs/11. Games/code-examples/canvas-game/styles.css
Fișierul nu include modificări și ar trebui să nu fie inclus în PR.

2024-12-22 19:22 UTC, liviucotfas commented on Labs/11. Games/code-examples/canvas-game/main.js
> +new Game();
S-ar putea renunța la această linie si sa fie păstrată cea de mai jos `window.game = new Game();`

2024-12-22 19:22 UTC, liviucotfas commented on Labs/11. Games/code-examples/canvas-game/src/Game.js
> +    // Prevent spiral of death
Ar fi necesară adăugarea de explicații suplimentare (sub formă de comentarii) pentru acest `if` sau adăugarea unui comentariu cu un link care să explice motivul comparației cu 250.

2024-12-22 19:22 UTC, liviucotfas commented on Labs/11. Games/code-examples/canvas-game/src/Game.js
> +  update(dt) {
Cred că ar fi bine dacă metoda ar avea un nume mai sugestiv, prin adaugarea a 1-2 cuvinte suplimentare la nume in afara de update.

2024-12-23 14:00 UTC, andreiserban123 commented
Buna ziua,

Am terminat de facut modificarile. Multumesc pentru feedback.

Daca mai este ceva de schimbat, va rog sa imi spuneti.

Multumes,

Andrei Serban

2024-12-23 19:37 UTC, merged